### ISSUE TITLE
less support

### ISSUE THREAD

**Issue by tjx666** [mat2ja/vue-ecosystem-snippets#12]
support `vstyle:less` like `vstyle:scss`.

Although sass is more popular then less, but still many top project using less, like ant design vue.

**Comment by mat2ja** [comment]
Done 👌🏻

Feel free to let me know if you find anything else missing, or feel like something could be improved.

**Comment by tjx666** [comment]
@mat2ja 

seems missing here:

![image](https://user-images.githubusercontent.com/41773861/212610466-41f6621e-36e9-4912-9913-1fc8eb20a6de.png)

**Comment by mat2ja** [comment]
Thank you, I missed that one. Added in [v0.5.5](https://github.com/mat2ja/vue-ecosystem-snippets/releases/tag/v0.5.5)
